apiVersion: v1
kind: Service
metadata:
  name: prt-services-simulator
  namespace: prt-simulator
  labels:
    app.kubernetes.io/name: prt-services-simulator
    app.kubernetes.io/component: simulator
spec:
  selector:
    app.kubernetes.io/name: prt-services-simulator
  type: ClusterIP
  ports:
    - name: http
      port: 8087
      targetPort: http
      protocol: TCP

